name: Dotnet
on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        dotnet: ['8.0.x']
    name: Dotnet ${{ matrix.dotnet }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install V8 on Ubuntu 
        if: matrix.os == 'ubuntu-latest' 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y libv8-dev 
      - name: Install V8 on macOS 
        if: matrix.os == 'macos-latest' 
        run: | 
          brew update 
          brew install v8 
      - name: Install V8 on Windows 
        if: matrix.os == 'windows-latest' 
        run: | 
          choco install v8
      - run: dotnet build MM2Randomizer.sln
      - run: dotnet test MM2Randomizer.sln --configuration Debug
      - run: dotnet test MM2Randomizer.sln --configuration Release
      - run: dotnet publish --runtime osx-x64 --configuration Release
      - run: dotnet publish --runtime linux-x64 --configuration Release
      - run: dotnet publish --runtime win-x64 --configuration Release
